name: supertuxkart
version: '1.1'
adopt-info: supertuxkart
icon: supertuxkart.png

grade: stable
confinement: strict
base: core18

apps:
  supertuxkart:
    command: desktop-launch libopenh264-launch $SNAP/usr/bin/supertuxkart
    desktop: usr/share/applications/supertuxkart.desktop
    common-id: supertuxkart.desktop
    environment:
      SUPERTUXKART_DATADIR: $SNAP/usr/share/supertuxkart
    plugs:
    - audio-playback
    - bluetooth-control
    - bluez
    - desktop
    - desktop-legacy
    - joystick
    - network
    - network-bind
    - opengl
    - pulseaudio
    - screen-inhibit-control
    - wayland
    - x11

layout:
  /etc/asound.conf:
    bind-file: $SNAP/etc/alsa.conf
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib

parts:
  alsa:
    source: https://github.com/diddledan/snapcraft-alsa.git
    plugin: nil
    override-pull: |
      cat > alsa.conf <<EOF
      pcm.!default {
        type pulse
        fallback "sysdefault"
        hint {
          show on
          description "Default ALSA Output (currently PulseAudio Sound Server)"
        }
      }
      ctl.!default {
        type pulse
        fallback "sysdefault"
      }
      EOF
    override-build: |
      snapcraftctl build
      install -m644 -D -t $SNAPCRAFT_PART_INSTALL/etc alsa.conf
    build-packages:
    - libasound2-dev
    stage-packages:
    - libasound2
    - libasound2-plugins

  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
    - libglib2.0-dev
    stage-packages:
    - libglib2.0-bin

  freetype-prebuild:
    source: https://download.savannah.gnu.org/releases/freetype/freetype-2.10.1.tar.xz
    source-checksum: sha256/16dbfa488a21fe827dc27eaf708f42f7aa3bb997d745d31a19781628c36ba26f
    plugin: autotools
    configflags:
    - --prefix=/usr/local
    - --with-harfbuzz=no
    build-packages:
    - libbz2-dev
    - libpng-dev
    - zlib1g-dev
    stage-packages:
    - libbz2-1.0
    - libpng16-16
    - zlib1g
    prime:
    - -*
  
  freetype:
    after: [freetype-prebuild, harfbuzz]
    source: https://download.savannah.gnu.org/releases/freetype/freetype-2.10.1.tar.xz
    source-checksum: sha256/16dbfa488a21fe827dc27eaf708f42f7aa3bb997d745d31a19781628c36ba26f
    plugin: autotools
    configflags:
    - --prefix=/usr
    - --with-harfbuzz=yes
    build-environment:
    - CFLAGS: -I$SNAPCRAFT_STAGE/usr/include/harfbuzz
    - CXXFLAGS: -I$SNAPCRAFT_STAGE/usr/include/harfbuzz
    build-packages:
    - libbz2-dev
    - libpng-dev
    - zlib1g-dev
    stage-packages:
    - libbz2-1.0
    - libpng16-16
    - zlib1g

  fontconfig:
    after: [freetype-prebuild]
    source: https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.13.1.tar.bz2
    source-checksum: sha256/f655dd2a986d7aa97e052261b36aa67b0a64989496361eca8d604e6414006741
    plugin: autotools
    configflags:
    - --prefix=/usr
    build-environment:
    - CFLAGS: -I$SNAPCRAFT_STAGE/usr/local/include/freetype2
    - CXXFLAGS: -I$SNAPCRAFT_STAGE/usr/local/include/freetype2
    - LDFLAGS: -L$SNAPCRAFT_STAGE/usr/lib -L$SNAPCRAFT_STAGE/usr/local/lib
    build-packages:
    - libexpat1-dev
    stage-packages:
    - libexpat1
    - libuuid1
    stage:
    - -usr/etc

  harfbuzz:
    after: [freetype-prebuild, fontconfig, icu]
    source: https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-2.6.4.tar.xz
    source-checksum: sha256/9413b8d96132d699687ef914ebb8c50440efc87b3f775d25856d7ec347c03c12
    plugin: autotools
    configflags:
    - --prefix=/usr
    - --with-fontconfig
    - --with-freetype
    - --with-graphite2
    - --with-icu
    build-environment:
    - CFLAGS: -I$SNAPCRAFT_STAGE/usr/local/include/freetype2
    - CXXFLAGS: -I$SNAPCRAFT_STAGE/usr/local/include/freetype2
    - LDFLAGS: -L$SNAPCRAFT_STAGE/usr/lib -L$SNAPCRAFT_STAGE/usr/local/lib
    build-packages:
    - gperf
    - libglib2.0-dev
    - libgraphite2-dev
    - uuid-dev
    stage-packages:
    - libglib2.0-bin
    - libgraphite2-3
    - libuuid1

  icu:
    source: https://github.com/unicode-org/icu/releases/download/release-65-1/icu4c-65_1-src.tgz
    source-checksum: sha256/53e37466b3d6d6d01ead029e3567d873a43a5d1c668ed2278e253b683136d948
    source-subdir: source
    plugin: autotools
    configflags:
    - --prefix=/usr

  libopenh264-helper:
    source: libopenh264-helper
    source-subdir: libopenh264
    plugin: make
    stage-packages:
    - bzip2
    - curl
    prime:
    - bin/bunzip2
    - bin/libopenh264-launch
    - usr/bin/curl
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libasn1*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libcurl-gnutls*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgssapi.so*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libhcrypto*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libheimbase*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libheimntlm*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libhx509*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/liblber*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libldap*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libroken*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/librtmp*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libsasl2*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libwind*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/sasl2

  libopenh264-library:
    plugin: make
    make-parameters:
    - PREFIX=/usr
    source: https://github.com/cisco/openh264/archive/v1.8.0.tar.gz
    build-packages:
    - g++
    - libasound-dev
    - libpulse-dev
    - nasm
    stage-packages:
    - libasound2
    - libpulse0
    override-build: |
      snapcraftctl build
      find $SNAPCRAFT_PART_INSTALL/usr/lib/pkgconfig -name "*openh264*.pc" -exec \
        sed -i "s|/usr/include|$SNAPCRAFT_STAGE/usr/include|g;s|/usr/lib|$SNAPCRAFT_STAGE/usr/lib|g" '{}' \;
    prime:
    - lib/libjson-c*
    - lib/libwrap*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libasound*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libasyncns*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libFLAC*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpulse*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libsndfile*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvorbisenc*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
    - usr/local/lib/libopenh264.so*

  libopenglrecorder:
    after: [libopenh264-library]
    plugin: cmake
    source: https://github.com/Benau/libopenglrecorder.git
    source-depth: 1
    configflags:
    - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
    - libturbojpeg0-dev
    - libogg-dev
    - libpulse-dev
    - libvorbis-dev
    - libvpx-dev
    stage-packages:
    - libturbojpeg
    - libogg0
    - libpulse0
    - libvorbisenc2
    - libvpx5

  supertuxkart:
    after:
    - freetype
    - harfbuzz
    - libopenglrecorder
    - libopenh264-library
    plugin: cmake
    source: https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/$SNAPCRAFT_PROJECT_VERSION/supertuxkart-$SNAPCRAFT_PROJECT_VERSION-src.tar.xz
    parse-info: [usr/share/metainfo/supertuxkart.appdata.xml]
    configflags:
    - -DCMAKE_INSTALL_PREFIX=/usr
    - -DENABLE_WAYLAND_DEVICE=ON
    build-environment:
    - CFLAGS: -I$SNAPCRAFT_STAGE/usr/include/freetype2
    - CXXFLAGS: -I$SNAPCRAFT_STAGE/usr/include/freetype2
    build-packages:
    - libbluetooth-dev
    - libcurl4-openssl-dev
    - libegl1-mesa-dev
    - libfribidi-dev
    - libgl1-mesa-dev
    - libgles2-mesa-dev
    - libjpeg-dev
    - libogg-dev
    - libopenal-dev
    - libpng-dev
    - libpulse-dev
    - libssl-dev
    - libvorbis-dev
    - libxrandr-dev
    - libwayland-dev
    - libxkbcommon-dev
    - subversion
    - zlib1g-dev
    stage-packages:
    - libbluetooth3
    - libcurl4
    - libdb5.3
    - libfribidi0
    - libgl1-mesa-glx
    - libgles2
    - libjpeg8
    - libogg0
    - libopenal1
    - libpng16-16
    - libpulse0
    - libssl1.1
    - libvorbis0a
    - libvorbisfile3
    - libxrandr2
    - libwayland-client0
    - libwayland-cursor0
    - libwayland-egl1-mesa
    - libxkbcommon0
    - zlib1g
    prime:
    - lib
    - usr/bin/supertuxkart
    - usr/lib
    - -usr/lib/gcc
    - -usr/lib/sasl2
    - usr/share/applications
    - usr/share/icons
    - usr/share/metainfo
    - usr/share/pixmaps
    - usr/share/supertuxkart
    - usr/share/X11
